# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-HTML-Widget-JavaScript
version:      0.01
version_from: lib/Catalyst/Plugin/HTML/Widget/JavaScript.pm
installdirs:  site
requires:
    Catalyst::Plugin::HTML::Widget: 0
    HTML::Widget::JavaScript:      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
